
package:
  name: codit
  version: "1.0.0"

source:
  git_rev: "1.0.0"
  git_url: git@github.com:jeremy-large/CODiT.git

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - numpy
    - pandas
    - scikit-learn
    - statsmodels
    - xlrd
    - matplotlib
    - jupyterlab
    - nbconvert
    - pydot
    - networkx

test:
  imports:
    - codit
  source_files:
    - tests/test_*.py
  requires:
    - pytest
  commands:
    - pytest tests/

about:
  home:  https://github.com/jeremy-large/CODiT
  license:  MIT
